apiVersion: v1
kind: Service
metadata:
  name: vue-golang-crud-db
  labels:
    app: vue-golang-crud-db
spec:
  clusterIP: None
  ports:
    - port: 5432
      name: vue-golang-crud-db
  selector:
    app: vue-golang-crud-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-golang-crud-db
  labels:
    app: vue-golang-crud-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vue-golang-crud-db
  template:
    metadata:
      labels:
        app: vue-golang-crud-db
    spec:
      containers:
      - name: vue-golang-crud-db
        image: registry.registry:5000/vue-golang-crud-db
        env:
          - name: POSTGRES_PASSWORD
            value: "test123456"
        ports:
        - containerPort: 5432
